backend:
  name: github
  repo: lilly0303/handoz
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections:
  - name: "fiction"
    label: " 同人文库 (Fiction)"
    folder: "site/content/fiction"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题 (Title)", name: "title", widget: "string"}
      - {label: "发布日期 (Date)", name: "date", widget: "datetime"}
      - {label: "标签 (Tags)", name: "tags", widget: "list", default: ["AU"]}
      - {label: "分级/预警 (Warning)", name: "warning", widget: "select", options: ["全年龄", "R15", "R18", "重度预警"], default: "全年龄"}
      - {label: "正文 (Content)", name: "body", widget: "markdown"}

  - name: "cinema"
    label: "影像档案馆 (Cinema)"
    folder: "site/content/cinema"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "视频标题 (Title)", name: "title", widget: "string"}
      - {label: "发布日期 (Date)", name: "date", widget: "datetime"}
      - {label: "B站嵌入代码 (Embed Code)", name: "embed", widget: "string", hint: "去B站网页端视频下方点击分享->嵌入代码，粘贴到这里"}
      - {label: "创作碎碎念 (Description)", name: "body", widget: "markdown", required: false}
